services:
  backend:
    image: mauricio0129/clouddrive-backend:latest  #renames bc of the build context presence
    build:
      context: .
      args:
        - ENVIRONMENT=prod
    ports:
      - "80:8080"
    environment:
      - ENVIRONMENT=production